# Generated by Django 3.1.1 on 2021-04-10 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.catagory'),
        ),
    ]
